Add deploy PR review workflow
security-summer-school/security-summer-school.github.io pull request #17
Opened 2022-09-29 20:53 UTC by gabrielmocanu

Add deploy PR review workflow

2022-09-30 05:56 UTC, gabrielmocanu commented
The link is: https://security-summer-school.github.io/pr-preview/pr-17/

2022-09-30 11:00 UTC, teodutu requested changes
The `.yml` file looks good AFAICT, but wy modify the `contributor-guideline.md` file?

2022-09-30 11:04 UTC, gabrielmocanu commented on content/en/docs/contribution-guidelines/contributor-guideline.md
> +## First Step
It was just a test to see how the PR preview looks.
I will revert this change.

2022-09-30 11:06 UTC, teodutu commented on content/en/docs/contribution-guidelines/contributor-guideline.md
> +## First Step
I see.

2022-09-30 11:06 UTC, teodutu approved these changes

2023-04-15 13:22 UTC, gabrielmocanu commented
I will close this PR since we won't need any PR to this repository.
All the updated are made through the bot when changes are in the main repositories.

2023-04-15 13:22 UTC, closed without merging